name: CI Compile-Only Demo

on:
  push:
    branches: [ main ]

jobs:
  compile-only:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Compile backend (allowed to fail)
        continue-on-error: true
        working-directory: Backend
        run: mvn clean compile

      - name: Compile frontend
        working-directory: frontend
        run: |
          npm ci --legacy-peer-deps
          npm run build
