name: CI Compile-Only

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compile-only:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Compile backend
        working-directory: Backend
        run: mvn clean compile

      - name: Compile frontend
        working-directory: frontend
        run: |
          npm ci
          npm run build
